### ISSUE TITLE
Signing Transactions Offline

### ISSUE THREAD

**Issue by emkman** [tomusdrw/rust-web3#116]
Support for signing transactions offline for sending to a locked node or potentially Infura would be extremely helpful. Similar functionality can be found in the `ethereumjs-tx` for javascript. Much of this functionality exists across the parity codebase and needs to be pieced together. In discussing this with @tomusdrw, the general steps required would be:

1.  Encode contract call (this can be done by `ethabi`)
2. Create and fill a transaction request (nonce, gas, gasprice, etc) - I believe there is an RPC method to do that in Parity
3. Encode the transaction into RLP
4. Calculate hash and sign (this could be done by `ethkey` library)
5. Broadcast signed transaction

**Comment by synlestidae** [comment]
Been interested in having this functionality since I came across the web3 crate. 

I propose we implement `web3::api::Eth::sign_transaction`:

`
pub fn sign_transaction(&self, transaction: &Transaction, private_key: H256) -> CallResult<Bytes, T::Out> { 
   // ...
}
`

As Transaction has redundant fields like `from` (derived from private key) and `hash` (computed from transaction), we could use a new struct. `UnsignedTransaction` perhaps.

As I understand it, Web3 just needs to call [signTransaction](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#signtransaction) with the right parameters. It'll take a bit of learning but I'd like to take this task :)

**Comment by synlestidae** [comment]
The output of `sign_transaction` would be the RLP-encoded transaction that can be fed into `send_raw_transaction`.

**Comment by tomusdrw** [comment]
Most likely integrate with https://github.com/tomusdrw/ethsign

**Comment by steveswing** [comment]
> Most likely integrate with https://github.com/tomusdrw/ethsign

We used ethsign with web3 indirectly -- in https://github.com/SubstratumNetwork/SubstratumNode -- but had to copy RawTransaction to work around type conflicts between web3::types, ethereum-types, and primitive-types.

**Comment by tomusdrw** [comment]
@steveswing cool! Yeah, there is no proper transaction type around (except for parity repo, but you really don't want to reference that in your code). I also wanted to avoid it in ethsign (initially), but would be happpy to include it at some point, along with different signature payloads that Ethereum is using (signData, signTransaction, etc)).
