### ISSUE TITLE
What's the generic way to manage web3 with different transport types?

### ISSUE THREAD

**Issue by 606simps** [tomusdrw/rust-web3#294]
Hi I am relatively new to rust and rust-web3. Now I see the example codes are like
```http
let (_eloop, http) = web3::transports::Http::new("http://localhost:8545").unwrap();
    let web3 = web3::Web3::new(http);
    let accounts = web3.eth().accounts().wait().unwrap();
```
```ws
let (_eloop, ws) = web3::transports::WebSocket::new("ws://localhost:8546").unwrap();
    let web3 = web3::Web3::new(ws);
    let accounts = web3.eth().accounts().wait().unwrap();
```
Which we need to create the transports with corresponding structures. Is there a generic way to create the transport without worrying what's the underlying transport? Which can accept different kinds of endpoints. Like below
```
let (_eloop, ws) = web3::transports::GenericTransport::new("ws://localhost:8546").unwrap();
    let web3 = web3::Web3::new(ws);
    let accounts = web3.eth().accounts().wait().unwrap();

let (_eloop, http) = web3::transports::GenericTransport::new("http://localhost:8545").unwrap();
    let web3 = web3::Web3::new(http);
    let accounts = web3.eth().accounts().wait().unwrap();
```
What I am seeing now is if I want to write codes supporting http and ws at the same time, I'll have to replicate every single line of code. What's the best way to reuse the code in the scenario?

Thanks!

**Comment by tomusdrw** [comment]
Hi @606simps! You have a few options to achieve that. You can either:
1. Write your functions in a generic way so that they support any `<T: Transport>`
2. Use `impl Trait` feature, using `web3:Web3<impl Transport>`, should be roughly the same as (1), but probably less code.
3. Use `Box`: `pub type Web3 = web3::Web3<Box<Transport>>`, this makes your code fully generic, but it might introduce an extra virtual call (but the performance impact is probably neglegible).

**Comment by vfusco** [comment]
Hi @tomusdrw and @606simps , I'm new to rust as well and trying to solve the same problem. I've tried these approaches without success. Maybe I'm missing something. What I was trying to do was something like:
```
pub struct ServiceContext {
    web3: web3::Web3<Box<dyn Transport>>
[...]
}

[...]

let ctx = ServiceContext {
    web3 = new_web3_transport(connstring),
...
}
```
But had problems with the associated type `Out` from `Transport` that I couldn't figure how to specify on the struct and on the return type of the `new_web3_transport`. The `connstring` here is the connection string for http or ws. I'm missing something?

**Comment by tomusdrw** [comment]
@vfusco @606simps Apologies, I mistakenly thought that `Box`ing the transport would be possible, but it seem that due to some early (not so wise) design decisions of the library, writing fully transport agnostic code without generics is not really possible.

I've made a workaround to this problem, if you know the transports you might be running on in advance. Have a look at this:
https://github.com/tomusdrw/rust-web3/pull/297/files#diff-8f217b8c4d4a1afd9933ab901657f0ddR5

Hope that's enough to address your problems.

**Comment by 606simps** [comment]
@tomusdrw Thanks this is a great example! I'll try to use it for my project.
