### ISSUE TITLE
Find better name for CallResult

### ISSUE THREAD

**Issue by debris** [tomusdrw/rust-web3#38]
https://github.com/tomusdrw/rust-web3/pull/35#discussion_r119070600

**Comment by InsidiousMind** [comment]
Since `CallResult` is a future, I'd advocate for renaming to simply `CallFuture` or `RPCFuture` or something along those lines. I think currently at first glance `CallResult` implies synchronous code that returns a wrapped `Result` type

I wouldn't mind refactoring the code if a name is decided upon

**Comment by debris** [comment]
I like `CallFuture`. What do you think @tomusdrw ?

**Comment by tomusdrw** [comment]
Sounds good!
