### ISSUE TITLE
eth_getFilterChanges not working because of malformed id

### ISSUE THREAD

**Issue by Steffen93** [tomusdrw/rust-web3#87]
Trying to capture events from a Smart Contract, I registered a Filter via `EthFilter.create_logs_filter(...)`.
The rpc responded with the filter id "0x03" which is internally transformed to a "3" as the id of the BaseFilter  struct. 
So when the filter changes are queried, it tries to query filter "0x3" instead of "0x**0**3", omitting the leading zero, which results in the rpc error: "FilterSubprovider - no filter with that id: 0x3".
It is possible to fix this by changing the BaseFilter id to type "String", but that might not be wanted.

This is the according output from ganache-cli:

```
# The library requests a new Filter:
eth_newFilter
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_newFilter",
   >   "params": [
   >     {
   >       ...
   >     }
   >   ],
   >   "id": 1,
   >   "external": true
   > }
...
# Response containing the Filter ID 0x03:
 <   {
 <     "id": 1,
 <     "jsonrpc": "2.0",
 <     "result": "0x03"
 <   }
...
# Filter Changes fail because of wrong ID, always returning empty JSON Array in the end
eth_getFilterChanges
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_getFilterChanges",
   >   "params": [
   >     "0x3"
   >   ],
   >   "id": 4,
   >   "external": true
   > }
FilterSubprovider - no filter with that id: 0x3
 <   {
 <     "id": 4,
 <     "jsonrpc": "2.0",
 <     "result": []
 <   }

```

Best regards,
hardliner93

**Comment by Steffen93** [comment]
Thanks a lot for the detailed reply and the instant fix. Great library you created there, I'm really relying on it :)
Keep it up!

**Comment by tomusdrw** [comment]
@Steffen93 Are you familar with ganache codebaase? Would be good to let them know that it's incorrect. I only found this instance: https://github.com/trufflesuite/ganache-core/blob/2b0b887cea8a6cb0a50fd4432685b5cbddd4f7a7/lib/subproviders/geth_api_double.js#L303
(should probably be using `to.rpcQuantityHexString` instead of `utils.addHexPrefix(utils.intToHex(`), but it seems to be a different method: `eth_newBlockFilter` vs `eth_newFilter`, I can't find the latter.

**Comment by Steffen93** [comment]
@tomusdrw I didn't know the codebase yet, but I will open an issue there and look where the right spot is.
