### ISSUE TITLE
Add rustfmt

### ISSUE THREAD

**Issue by tomusdrw** [tomusdrw/rust-web3#92]

**Comment by akuanti** [comment]
What does this mean? Add a `rustfmt.toml`? Add it to the build process?

**Comment by tomusdrw** [comment]
@akuanti Yup:
- [ ] Add `rustfmt.toml` with settings that attempt to reflect current coding style as much as possible
- [ ] Reformat the code base
- [ ] Ensure that incorrectly formatted code does not reach `master` (so a check during build if possible)

**Comment by mjkoo** [comment]
Given #12 is there opposition to using the rustfmt defaults?

**Comment by tomusdrw** [comment]
@mjkoo let's try it out!

**Comment by mjkoo** [comment]
Cool, ran `cargo fmt` on master with a `rustfmt.toml` that extends the max line width (otherwise it chokes on the extremely long strings in the eth unit tests etc), also added `cargo fmt ...` to the travis config so it gets run as part of CI.

Results are at https://github.com/tomusdrw/rust-web3/compare/master...polyswarm:rustfmt , diff is rather gross as expected due to reformatting the whole crate.

Might be best to do this again after some of the PRs in motion are merged?

**Comment by tomusdrw** [comment]
Cool. Please submit a PR, I will mark it as "on ice" and merge it after we have all other PRs merged.

**Comment by thomaseizinger** [comment]
I guess this should now be closed?

**Comment by tomusdrw** [comment]
Yup, thanks!
